//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddToDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_list
    {
        public long id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public long IdMaterial { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> IdResponsibleWorker { get; set; }
    
        public virtual material_list material_list { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
