//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1Pr3
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_list
    {
        public long id { get; set; }
        public long product_id { get; set; }
        public long material_id { get; set; }
    
        public virtual material_list material_list { get; set; }
        public virtual product_list product_list { get; set; }
    }
}
